### PR TITLE
Fix synchronization in allreduce8 kernel

### PR DESCRIPTION
**Pull request by dsidler**
Running kernel allreduce8 across 64 vGPUs (in CPX mode) revealed a synchronization bug. The PR addresses it by ensuring that signals are only issued after all threads in the block have issued their writes to guarantee correct ordering between data writes and signal writes.

### CODE REVIEW

**Comment by dsidler** [comment]
@microsoft-github-policy-service agree [company="Advanced Micro Devices, Inc."]

**Comment by dsidler** [comment]
@microsoft-github-policy-service agree company="Advanced Micro Devices, Inc."

**Review by chhwang — APPROVED** [review]

**Pull request merged**
